"""
Django settings for spolem project.

Generated by 'django-admin startproject' using Django 3.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pe)u+s9w+s^srefry202r*56q8zt=u976&gjjyh7h2d6(=^i2*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.68.108', 'localhost', '10.10.0.85',
                 '10.0.0.63', '10.10.0.41', '192.168.68.112', '10.0.0.115']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'kalendarz',
    'towary',
    'promocje',
    'sklepy',
    'pracownicy',
    'prominfo',
    'promcent',
    'promczas_cent',
    'promczas_sklep',
    'promczas_info',
    'pracownicyplac',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # CORS
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
]

CORS_ORIGIN_WHITELIST = (
    'http://localhost:4200',
    'http://192.168.68.105:4200',
    'http://10.10.0.154:4200',
    'http://10.0.0.71:4200',
    'http://192.168.68.0:4200',
    'http://10.10.0.85:4200',
    'http://10.0.0.115:4200',

)
ROOT_URLCONF = 'spolem.urls'
CORS_ORIGIN_ALLOW_ALL = True


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'spolem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'spolkal',
        'USER': 'tomasz',
        'PASSWORD': 'Muct0CzM',
        'HOST': 'localhost',
        'PORT': '5432',
    },
    'sklep1': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep1'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep2': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep2'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep3': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep3'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep6': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep6'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep7': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep7'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep12': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep12'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep13': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep13'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep14': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep14'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep19': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep19'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep23': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep23'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sklep27': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sklep27'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'sdh2p': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=sdh2p'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    },
    'centrala': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=centrala'
        },

        # 'NAME': 'spolkal',
        'NAME': 'centrala',
        # 'USER': 'tomasz',
        # 'USER': 'kali',
        'USER': 'tomek',
        # 'PASSWORD': 'Muct0CzM',
        'PASSWORD': '1qazxsw2',
        'HOST': '10.10.0.145',
        'PORT': '5432',
    }
}

DATABASE_ROUTERS = ['kalendarz.routers.kalendarzRouter']

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'pl-PL'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
